### ISSUE TITLE
Rule proposal

### ISSUE THREAD

**Issue by kentcdodds** [jlengstorf/eslint-plugin-replyguy#2]
Actually two rules. The first asks you what font you're using. The second asks you what theme. These rules would never be satisfied in an effort to resemble reality best.

**Comment by jlengstorf** [comment]
😂 

these could be stacked on `Program` so they’re always triggered. this would be a great first contribution for someone interested in learning how to build ESLint rules and/or how to be a Reply Guy!

**Comment by ajstrand** [comment]
@jlengstorf I'd be happy to work on this issue. If I have questions, I'll let you know here, although the eslint docs seem pretty comprehensive.

**Comment by jlengstorf** [comment]
@ajstrand I would highly recommend https://astexplorer.net/ with the `babel-eslint` setting and the transform set to ESLint v4 — it makes writing rules a lot more approachable!

@kentcdodds also has a [workshop on ASTs](https://github.com/kentcdodds/asts-workshop) if you want to dig deeper!

<img width="949" alt="Screen Shot 2020-08-08 at 5 16 23 PM" src="https://user-images.githubusercontent.com/163561/89722147-e77ad800-d99a-11ea-8653-f21be6aff12f.png">

**Comment by ajstrand** [comment]
@jlengstorf thanks for the recommendations!
