### ISSUE TITLE
All jsx files should have .jsx as the extension

### ISSUE THREAD

**Issue by fimion** [jlengstorf/eslint-plugin-replyguy#8]
Because it's just clearer that way, you know. Like, only a fool would put jsx in a .js file.

**Comment by OmarMoataz** [comment]
Please don't help this madness! 😄

**Comment by judicaelandria** [comment]
can someone guide me a little bit so I can take this issue? please :)

**Comment by RaiVaibhav** [comment]
Hello team and Hi @judicaelandria  you can start by
- Looking at how AST plays a role at eslint https://github.com/kentcdodds/asts-workshop
- After having an overview of how does `context` and `node` play a role, you should look at the https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-filename-extension.js, this will guide you on writing the rule.

**Comment by judicaelandria** [comment]
The rules in yannickcr do this exactly, can I follow how is he doing it?

**Comment by judicaelandria** [comment]
how to test if my codes work, or I just submit a PR, and you'll tell me if I should change something?

**Comment by judicaelandria** [comment]
> how to test if my codes work, or I just submit a PR, and you'll tell me if I should change something?
sorry about all this question, I'm new in open source worl :(

**Comment by judicaelandria** [comment]
> > how to test if my codes work, or I just submit a PR, and you'll tell me if I should change something?
> > sorry about all this question, I'm new in open source world :(

**Comment by judicaelandria** [comment]
@jlengstorf  maybe we can close this now?

**Comment by jlengstorf** [comment]
closed by #10
